# Generated by Django 5.1.7 on 2025-03-25 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currentlocation', models.JSONField()),
                ('pickup', models.JSONField()),
                ('dropoff', models.JSONField()),
                ('ways', models.JSONField()),
                ('totaldistance', models.FloatField()),
                ('total_time_driving', models.TimeField(blank=True, null=True)),
                ('datetimeUTC', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'tripconfig',
            },
        ),
        migrations.CreateModel(
            name='TripBreak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.JSONField()),
                ('begin', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('reason', models.CharField(choices=[('stop', 'Stop'), ('rest', 'Rest')], max_length=10)),
                ('tripconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.tripconfig')),
            ],
            options={
                'db_table': 'tripbreak',
            },
        ),
        migrations.CreateModel(
            name='TripRefueling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gasstationlocation', models.JSONField()),
                ('distancetodropoff', models.FloatField()),
                ('tripconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.tripconfig')),
            ],
            options={
                'db_table': 'triprefueling',
            },
        ),
    ]
