# Generated by Django 5.1.7 on 2025-05-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_tripbreak_reason_alter_tripconfig_datetimeutc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripbreak',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tripconfig',
            name='currentlocation',
        ),
        migrations.RemoveField(
            model_name='tripconfig',
            name='dropoff',
        ),
        migrations.RemoveField(
            model_name='tripconfig',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='tripdriving',
            name='begin_location',
        ),
        migrations.RemoveField(
            model_name='tripdriving',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='triprefueling',
            name='gasstationlocation',
        ),
    ]
