# Generated by Django 5.1.7 on 2025-04-01 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbreak',
            name='reason',
            field=models.CharField(choices=[('rest', 'Rest'), ('refuel', 'Refuel'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tripconfig',
            name='datetimeUTC',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='TripDriving',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('begin_location', models.JSONField()),
                ('end_location', models.JSONField()),
                ('time_total', models.TimeField()),
                ('begin', models.DateTimeField()),
                ('tripconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.tripconfig')),
            ],
            options={
                'db_table': 'tripdriving',
            },
        ),
    ]
